### ISSUE TITLE
Game crashes on launch

### ISSUE THREAD

**Issue by gatts101** [willatendo/Fossils-And-Archaeology-Legacy#10]
Every time I try to launch it crashes

Here's the full crash report:

---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 2024-08-12 13:38:37
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'fossilslegacy'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:403)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:401)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:477)
	at net.minecraft.client.main.Main.main(Main.java:239)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2378.method_30517()" because "$$0" is null
	at net.minecraft.class_2378.method_10230(class_2378.java:126)
	at willatendo.simplelibrary.server.event.FabricRegisterRegister.register(FabricRegisterRegister.java:13)
	at willatendo.simplelibrary.server.registry.SimpleRegistry.addEntries(SimpleRegistry.java:48)
	at willatendo.simplelibrary.server.event.FabricSimpleRegistryRegister.register(FabricSimpleRegistryRegister.java:8)
	at willatendo.fossilslegacy.FossilsLegacyMod.onInitialize(FossilsLegacyMod.java:36)
	at willatendo.fossilslegacy.FossilsLegacyFabricMod.onInitialize(FossilsLegacyFabricMod.java:13)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399)
	... 6 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:403)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:401)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:477)

-- Initialization --
Details:
	Modules: 
		ADVAPI32.dll:Advanced Windows 32 Base API:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		COMCTL32.dll:User Experience Controls Library:6.10 (WinBuild.160101.0800):Microsoft Corporation
		CRYPT32.dll:Crypto API32:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		CRYPTBASE.dll:Base cryptographic API DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		CRYPTSP.dll:Cryptographic Service Provider API:10.0.22621.2706 (WinBuild.160101.0800):Microsoft Corporation
		DBGHELP.DLL:Windows Image Helper:10.0.22621.2706 (WinBuild.160101.0800):Microsoft Corporation
		DNSAPI.dll:DNS Client API DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		GDI32.dll:GDI Client DLL:10.0.22621.2706 (WinBuild.160101.0800):Microsoft Corporation
		IMM32.DLL:Multi-User Windows IMM32 API Client DLL:10.0.22621.2706 (WinBuild.160101.0800):Microsoft Corporation
		IPHLPAPI.DLL:IP Helper API:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		KERNEL32.DLL:Windows NT BASE API Client DLL:10.0.22621.2706 (WinBuild.160101.0800):Microsoft Corporation
		KERNELBASE.dll:Windows NT BASE API Client DLL:10.0.22621.2706 (WinBuild.160101.0800):Microsoft Corporation
		MpOav.dll:IOfficeAntiVirus Module:4.18.24070.5 (e798126f926dd886b32c6c109a80cc3baf14090c):Microsoft Corporation
		NSI.dll:NSI User-mode interface DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		NTASN1.dll:Microsoft ASN.1 API:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		OLEAUT32.dll:OLEAUT32.DLL:10.0.22621.2706 (WinBuild.160101.0800):Microsoft Corporation
		Ole32.dll:Microsoft OLE for Windows:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		POWRPROF.dll:Power Profile Helper DLL:10.0.22621.2706 (WinBuild.160101.0800):Microsoft Corporation
		PSAPI.DLL:Process Status Helper:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		Pdh.dll:Windows Performance Data Helper DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		RPCRT4.dll:Remote Procedure Call Runtime:10.0.22621.2706 (WinBuild.160101.0800):Microsoft Corporation
		SHCORE.dll:SHCORE:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		SHELL32.dll:Windows Shell Common Dll:10.0.22621.2776 (WinBuild.160101.0800):Microsoft Corporation
		UMPDC.dll:User Mode Power Dependency Coordinator:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		USER32.dll:Multi-User Windows USER API Client DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		USERENV.dll:Userenv:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		VCRUNTIME140.dll:Microsoft® C Runtime Library:14.29.30139.0 built by: vcwrkspc:Microsoft Corporation
		VERSION.dll:Version Checking and File Installation Libraries:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		WINHTTP.dll:Windows HTTP Services:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		WINMM.dll:MCI API DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		WS2_32.dll:Windows Socket 2.0 32-Bit DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		amsi.dll:Anti-Malware Scan Interface:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		bcrypt.dll:Windows Cryptographic Primitives Library:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		bcryptPrimitives.dll:Windows Cryptographic Primitives Library:10.0.22621.2706 (WinBuild.160101.0800):Microsoft Corporation
		clbcatq.dll:COM+ Configuration Catalog:2001.12.10941.16384 (WinBuild.160101.0800):Microsoft Corporation
		combase.dll:Microsoft COM for Windows:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		dbgcore.DLL:Windows Core Debugging Helpers:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		dxcore.dll:DXCore:10.0.22621.2706 (WinBuild.160101.0800):Microsoft Corporation
		extnet.dll:OpenJDK Platform binary:21.0.3.0:Microsoft
		fwpuclnt.dll:FWP/IPsec User-Mode API:10.0.22621.2706 (WinBuild.160101.0800):Microsoft Corporation
		gdi32full.dll:GDI Client DLL:10.0.22621.2706 (WinBuild.160101.0800):Microsoft Corporation
		glfw.dll:GLFW 3.4.0 DLL:3.4.0:GLFW
		java.dll:OpenJDK Platform binary:21.0.3.0:Microsoft
		javaw.exe:OpenJDK Platform binary:21.0.3.0:Microsoft
		jemalloc.dll
		jimage.dll:OpenJDK Platform binary:21.0.3.0:Microsoft
		jli.dll:OpenJDK Platform binary:21.0.3.0:Microsoft
		jna3819696232769314590.dll:JNA native library:7.0.0:Java(TM) Native Access (JNA)
		jsvml.dll:OpenJDK Platform binary:21.0.3.0:Microsoft
		jvm.dll:OpenJDK 64-Bit server VM:21.0.3.0:Microsoft
		kernel.appcore.dll:AppModel API Host:10.0.22621.2771 (WinBuild.160101.0800):Microsoft Corporation
		lwjgl.dll
		management.dll:OpenJDK Platform binary:21.0.3.0:Microsoft
		management_ext.dll:OpenJDK Platform binary:21.0.3.0:Microsoft
		msvcp140.dll:Microsoft® C Runtime Library:14.29.30139.0 built by: vcwrkspc:Microsoft Corporation
		msvcp_win.dll:Microsoft® C Runtime Library:10.0.22621.2706 (WinBuild.160101.0800):Microsoft Corporation
		msvcrt.dll:Windows NT CRT DLL:7.0.22621.2706 (WinBuild.160101.0800):Microsoft Corporation
		mswsock.dll:Microsoft Windows Sockets 2.0 Service Provider:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		napinsp.dll:E-mail Naming Shim Provider:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		ncrypt.dll:Windows NCrypt Router:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		net.dll:OpenJDK Platform binary:21.0.3.0:Microsoft
		nio.dll:OpenJDK Platform binary:21.0.3.0:Microsoft
		nlansp_c.dll:NLA Namespace Service Provider DLL:10.0.22621.2706 (WinBuild.160101.0800):Microsoft Corporation
		ntdll.dll:NT Layer DLL:10.0.22621.2706 (WinBuild.160101.0800):Microsoft Corporation
		perfos.dll:Windows System Performance Objects DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		pfclient.dll:SysMain Client:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		pnrpnsp.dll:PNRP Name Space Provider:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		profapi.dll:User Profile Basic API:10.0.22621.2706 (WinBuild.160101.0800):Microsoft Corporation
		rasadhlp.dll:Remote Access AutoDial Helper:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		rsaenh.dll:Microsoft Enhanced Cryptographic Provider:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		sechost.dll:Host for SCM/SDDL/LSA Lookup APIs:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		shlwapi.dll:Shell Light-weight Utility Library:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		sunmscapi.dll:OpenJDK Platform binary:21.0.3.0:Microsoft
		ucrtbase.dll:Microsoft® C Runtime Library:10.0.22621.2706 (WinBuild.160101.0800):Microsoft Corporation
		vcruntime140_1.dll:Microsoft® C Runtime Library:14.29.30139.0 built by: vcwrkspc:Microsoft Corporation
		verify.dll:OpenJDK Platform binary:21.0.3.0:Microsoft
		win32u.dll:Win32u:10.0.22621.2706 (WinBuild.160101.0800):Microsoft Corporation
		windows.storage.dll:Microsoft WinRT Storage API:10.0.22621.2706 (WinBuild.160101.0800):Microsoft Corporation
		winrnr.dll:LDAP RnR Provider DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		wintypes.dll:Windows Base Types DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		wshbth.dll:Windows Sockets Helper DLL:10.0.22621.2706 (WinBuild.160101.0800):Microsoft Corporation
		zip.dll:OpenJDK Platform binary:21.0.3.0:Microsoft
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:239)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- System Details --
Details:
	Minecraft Version: 1.21
	Minecraft Version ID: 1.21
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 21.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 268549864 bytes (256 MiB) / 805306368 bytes (768 MiB) up to 12884901888 bytes (12288 MiB)
	CPUs: 16
	Processor Vendor: GenuineIntel
	Processor Name: 13th Gen Intel(R) Core(TM) i7-1360P
	Identifier: Intel64 Family 6 Model 186 Stepping 2
	Microarchitecture: Raptor Lake
	Frequency (GHz): 2.61
	Number of physical packages: 1
	Number of physical CPUs: 12
	Number of logical CPUs: 16
	Graphics card #0 name: Intel(R) Iris(R) Xe Graphics
	Graphics card #0 vendor: Intel Corporation
	Graphics card #0 VRAM (MiB): 1024.00
	Graphics card #0 deviceId: VideoController1
	Graphics card #0 versionInfo: 31.0.101.4314
	Memory slot #0 capacity (MiB): 2048.00
	Memory slot #0 clockSpeed (GHz): 6.40
	Memory slot #0 type: Unknown
	Memory slot #1 capacity (MiB): 2048.00
	Memory slot #1 clockSpeed (GHz): 6.40
	Memory slot #1 type: Unknown
	Memory slot #2 capacity (MiB): 2048.00
	Memory slot #2 clockSpeed (GHz): 6.40
	Memory slot #2 type: Unknown
	Memory slot #3 capacity (MiB): 2048.00
	Memory slot #3 clockSpeed (GHz): 6.40
	Memory slot #3 type: Unknown
	Memory slot #4 capacity (MiB): 2048.00
	Memory slot #4 clockSpeed (GHz): 6.40
	Memory slot #4 type: Unknown
	Memory slot #5 capacity (MiB): 2048.00
	Memory slot #5 clockSpeed (GHz): 6.40
	Memory slot #5 type: Unknown
	Memory slot #6 capacity (MiB): 2048.00
	Memory slot #6 clockSpeed (GHz): 6.40
	Memory slot #6 type: Unknown
	Memory slot #7 capacity (MiB): 2048.00
	Memory slot #7 clockSpeed (GHz): 6.40
	Memory slot #7 type: Unknown
	Virtual memory max (MiB): 28231.93
	Virtual memory used (MiB): 19706.11
	Swap memory total (MiB): 12288.00
	Swap memory used (MiB): 755.30
	Space in storage for jna.tmpdir (MiB): available: 776544.38, total: 956244.00
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): available: 776544.38, total: 956244.00
	Space in storage for io.netty.native.workdir (MiB): available: 776544.38, total: 956244.00
	Space in storage for java.io.tmpdir (MiB): available: 776544.38, total: 956244.00
	Space in storage for workdir (MiB): available: 776544.38, total: 956244.00
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx12G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		ambientsounds: AmbientSounds 6.0.4
		antique-atlas: Antique Atlas 2.9.12+1.21
			surveyor: Surveyor Map Framework 0.6.11+1.21
		appleskin: AppleSkin 3.0.2+mc1.21
		architectury: Architectury 13.0.6
		astrocraft: Astrocraft 1.3.2+1.21
		bagofholding: Bag Of Holding 21.0.1
			iteminteractions: Item Interactions 21.0.3
		balm-fabric: Balm 21.0.14
			kuma_api: KumaAPI 21.0.4
		better_climbing: Better Climbing 3
		betterclouds: Better Clouds 1.7.1+1.21
		betterdays: BetterDays 3.1.0.6
			spectrelib: SpectreLib 0.17.2+1.21
		betterthirdperson: Better Third Person 1.9.0
		boids: Boids 1.2.3
			blue_endless_jankson: jankson 1.2.3
		brainierbees: Brainier Bees 1.6
		carryon: Carry On 2.2.1
		catnipfabric: Catnip Fabric 1.0
		cavedust: Cave Dust 3.0.0
			kirin: Kirin UI 1.19.0+1.21
		cloth-config: Cloth Config v15 15.0.128
			cloth-basic-math: cloth-basic-math 0.6.1
		collective: Collective 7.80
		connectiblechains: Connectible Chains 2.4.1+1.21
		continuity: Continuity 3.0.0-beta.5+1.21
		creativecore: CreativeCore 2.12.4
			net_neoforged_bus: bus 7.2.0
		cropsloverain: Crops Love Rain 2.1.1
			midnightlib: MidnightLib 1.5.7
		ctrl-q: Ctrl Q 1.9
		cullleaves: Cull Leaves 3.4.0
		cupboard: cupboard 1.21-2.7
		damagenumbers: Damage Numbers 1.4.1-fabric
		dark_title_bar: DarkTitleBar 1.3
		darkness: True Darkness Refabricated 1.0.6
		durabilitytooltip: Durability Tooltip 1.1.5
		dynamiccrosshair: Dynamic Crosshair 8.0.2+1.21
			dynamiccrosshair-api: DynamicCrosshair API ${api_version}
			libbamboo: libbamboo 1.21.0.1
		e4mc_minecraft: e4mc 5.1.0
			folk_sisby_kaleido-config: kaleido-config 0.3.1+1.3.1
		easyanvils: Easy Anvils 21.0.2
		easymagic: Easy Magic 21.0.1
		eatinganimationid: Eating Animation 1.21+1.9.72
		elytraslot: Elytra Slot 9.0.0+1.21
			mixinsquared: MixinSquared 0.1.2-beta.6
		entity_model_features: Entity Model Features 2.1.3
		entity_texture_features: Entity Texture Features 6.1.3
			org_apache_httpcomponents_httpmime: httpmime 4.5.10
		entityculling: EntityCulling 1.6.6
		explosiveenhancement: Explosive Enhancement 1.2.3-1.21.0
		fabric-api: Fabric API 0.100.7+1.21
			fabric-api-base: Fabric API Base 0.4.42+6573ed8cd1
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.67+b5597344d1
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.29+5bd9f1bcd1
			fabric-block-api-v1: Fabric Block API (v1) 1.0.22+0af3f5a7d1
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.10+6573ed8cd1
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.52+0af3f5a7d1
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.15+6573ed8cd1
			fabric-command-api-v1: Fabric Command API (v1) 1.2.49+f71b366fd1
			fabric-command-api-v2: Fabric Command API (v2) 2.2.28+6ced4dd9d1
			fabric-commands-v0: Fabric Commands (v0) 0.2.66+df3654b3d1
			fabric-content-registries-v0: Fabric Content Registries (v0) 8.0.15+b5597344d1
			fabric-convention-tags-v1: Fabric Convention Tags 2.0.18+7f945d5bd1
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.4.2+c111832ad1
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.29+0af3f5a7d1
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.1.25+6a6dfa19d1
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 20.2.12+16c4ae25d1
			fabric-dimensions-v1: Fabric Dimensions API (v1) 4.0.0+6fc22b99d1
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.12+6fc22b99d1
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.10+e633f883d1
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.53+6ced4dd9d1
			fabric-item-api-v1: Fabric Item API (v1) 11.0.0+afdfc921d1
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.3+78017270d1
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.47+0af3f5a7d1
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.45+df3654b3d1
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.3.11+8f3583aed1
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.13+3f89f5a5d1
			fabric-loot-api-v3: Fabric Loot API (v3) 1.0.1+3f89f5a5d1
			fabric-message-api-v1: Fabric Message API (v1) 6.0.13+6573ed8cd1
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 2.0.0+fe474d6bd1
			fabric-networking-api-v1: Fabric Networking API (v1) 4.2.0+ab7edbacd1
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 15.1.13+d1321076d1
			fabric-particles-v1: Fabric Particles (v1) 4.0.2+6573ed8cd1
			fabric-recipe-api-v1: Fabric Recipe API (v1) 5.0.10+65089712d1
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.0.25+5bd9f1bcd1
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.3.0+0ae0b97dd1
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.6.5+48fb1586d1
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.68+df3654b3d1
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.48+73761d2ed1
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.6+b5597344d1
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.71+df3654b3d1
			fabric-rendering-v1: Fabric Rendering (v1) 5.0.5+df16efd0d1
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 4.2.1+d153f344d1
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 1.2.0+7e687b32d1
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.24+b5597344d1
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.82+b5597344d1
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.23+6573ed8cd1
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.1.15+3dccd343d1
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.0.12+6573ed8cd1
		fabric-language-kotlin: Fabric Language Kotlin 1.11.0+kotlin.2.0.0
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 2.0.0
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 2.0.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 2.0.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 2.0.0
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.24.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.8.1
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.8.1
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.6.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.6.3
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.6.3
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.6.3
		fabricloader: Fabric Loader 0.16.0
			mixinextras: MixinExtras 0.4.0
		fallingtrees: Falling Trees 0.12.3
		fancyhealthbar: FancyHealthBar 1.1.0
		firstperson: FirstPerson 2.4.3
		forgeconfigapiport: Forge Config API Port 21.0.5
			com_electronwill_night-config_core: core 3.8.0
			com_electronwill_night-config_toml: toml 3.8.0
		fossilslegacy: Fossils and Archaeology Legacy 1.3.2
			mm: Manningham Mills 2.3
			simplelibrary: SimpleLibrary 3.9.2
		geckolib: GeckoLib 4 4.5.7
		growable_ores: Skniro's GrowableOres 2.4.0-1.21-Fabric
		head_in_the_clouds: Head In The Clouds 1.1.0
		horsebuff: HorseBuff 2.1.8
		immediatelyfast: ImmediatelyFast 1.2.18+1.21
			net_lenni0451_reflect: Reflect 1.3.4
		immersiveui: ImmersiveUI 0.1.1
		indium: Indium 1.0.34+mc1.21
		invmove: InvMove 0.8.8
		jade: Jade 15.1.3+fabric
		jamlib: JamLib 1.0.9+1.21
		java: OpenJDK 64-Bit Server VM 21
		jei: Just Enough Items 19.5.0.61
		kiss: Keep Inventory Sorted, Simple 0.1
			kyrptconfig: Kyrpt Config 1.6.1-1.20.4
		kiwi: Kiwi Library 15.1.0+fabric
		knightquest: Knight Quest 1.4.1
		leafmealone: Leaf Me Alone 1.0.1
		leahs-immersive-thunder: Immersive Thunder 1.21+1.2.2
		lightingwand: Lighting Wand 9.0.2+fabric
		linearxp: Linear XP 1.0.1
		litematica: Litematica 0.18.999-sakura.26
		litematica-printer: Litematica Printer 3.5.0-sakura.2
		logprot: Logprot Mod 1.21-3.4
		magistuarmory: Epic Knights: Shields, Armor and Weapons 9.14
		malilib: MaLiLib 0.20.0
		minecraft: Minecraft 1.21
		mining_dims: Mining Dimensions 1.7.12
		modelfix: Model Gap Fix 1.21-1.6
		modmenu: Mod Menu 11.0.1
			placeholder-api: Placeholder API 2.4.0-pre.2+1.21
		moreculling: More Culling 0.26.0
			com_github_fallen-breath_conditional-mixin: conditional-mixin v0.6.2
		mousetweaks: Mouse Tweaks 2.26
		mr_2032_worldheight: 2032 World Height 1.20.5+
		mr_animated_doors: Animated Doors 1.21
		mr_better_trees: Better Trees 1.8.1
		mr_bigger_catsandrabbits: Bigger Cats and Rabbits 1.0
		mr_desert_scourge: Desert Scourge 1.1
		mr_dynamic_torches: Dynamic Torches 4
		mr_happysheep: HappySheep 1.1
		mr_omnicut_betterwoodstonecutter: OmniCut: Better Wood and Stone Cutter 1.48.0
		naturescompass: Nature's Compass 1.21-2.2.6-fabric
		nbc_mr: Netherite But Cheaper 1.0
		nerb: Not Enough Recipe Book 0.4
		nocturnal-bats: Nocturnal Bats 1.0.0+1.19.4
		nohotbarlooping: No Hotbar Looping 1.1.1
		noisium: Noisium 2.2.1+mc1.21
		notenoughanimations: NotEnoughAnimations 1.7.4
		nyfsspiders: Nyf's Spiders 2.3.0
			commonnetworking: Common Network 1.0.11-1.21
		onlyhammers: OnlyHammers 1.21-0.3
		pandalib: PandaLib 0.3
		particlerain: Particle Rain 2.1.2
		peepingcreepers: Peeping Creepers 1.2-1.20.5
		plantsjunk: Plants&Junk 1.0.1-1.21
			terraform-wood-api-v1: Terraform Wood API (v1) 11.0.0-alpha.1
		pling: Pling 1.8.1
		presencefootsteps: Presence Footsteps 1.10.0+1.21
		prettybeaches: Pretty Beaches 21.0.2
		pulchra-occultorum: Pulchra Occultorum 0.0.8
		puzzleslib: Puzzles Lib 21.0.17
		rallyhealth: Rally Health 2.0.0
		random_mob_sizes: Random Mob Sizes 1.21-2.2.0
		reacharound: Reacharound 1.3.0
		realisticbees: Realistic Bees 3.9
		realmsfix: Realms Button Remover 2.0.4
		reaping: Reaping 3.1.0+1.21
		reinfchest: Reinforced Chests 3.0.1+1.21
			reinfcore: Reinforced Core 4.0.1+1.21
		reputation: Your Reputation 0.2.7+jade.1.21
		rightclickharvest: Right Click Harvest 4.3.1+1.21
		selfcare-hive: Self-Care Hive 1.0.2+1.20.5
		simplefog: Simple Fog Control 1.6.0
		skinlayers3d: 3d-Skin-Layers 1.6.6
		sodium: Sodium 0.5.11+mc1.21
		sound_physics_remastered: Sound Physics Remastered 1.21-1.4.5
		spirit-vector: Dream Burst Spirit Vector 1.7.0
		stutterfix: StutterFix mc1.21-0.2.2
		supermartijn642configlib: SuperMartijn642's Config Lib 1.1.8
		supermartijn642corelib: SuperMartijn642's Core Lib 1.1.17
		timm: The Immersive Music Mod 1.0.3
		trashcans: Trash Cans 1.0.18
			team_reborn_energy: Energy 4.1.0
		trimeffects: TrimsEffects 1.3.1
		trinkets: Trinkets 3.10.0
			cardinal-components-base: Cardinal Components API (base) 6.1.0
			cardinal-components-entity: Cardinal Components API (entities) 6.1.0
		trowel: Trowel 1.4.0
		twerk4fabric: Twerk4Fabric 1.0.0
		unloadedactivity: Unloaded Activity 0.6.2
		vanityslots: Vanity Slots 1.4.0+1.21
		villager-pickup: Villager Pickup 1.1.2
		visualworkbench: Visual Workbench 21.0.1
		wooltostring: Wool to String 1.0.1
		yet_another_config_lib_v3: YetAnotherConfigLib 3.5.0+1.21-fabric
			com_twelvemonkeys_common_common-image: common-image 3.10.0
			com_twelvemonkeys_common_common-io: common-io 3.10.0
			com_twelvemonkeys_common_common-lang: common-lang 3.10.0
			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0
			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0
			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0
			org_quiltmc_parsers_gson: gson 0.2.1
			org_quiltmc_parsers_json: json 0.2.1
		zoomify: Zoomify 2.14.0+1.21
			com_akuleshov7_ktoml-core-jvm: ktoml-core-jvm 0.5.1
	Launched Version: fabric-loader-0.16.0-1.21
	Launcher name: minecraft-launcher
	Backend library: LWJGL version 3.3.3-snapshot
	Backend API: Unknown
	Window size: <not initialized>
	GFLW Platform: <error>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Is Modded: Definitely; Client brand changed to 'fabric'
	Universe: 404
	Type: Client (map_client.txt)
	Locale: en_US
	System encoding: Cp1252
	File encoding: UTF-8
	CPU: <unknown>

**Comment by gatts101** [comment]
Wow that was really quick, I appreciate it!
