### ISSUE TITLE
Server fails to start on launch.

### ISSUE THREAD

**Issue by RedOptic** [willatendo/Fossils-And-Archaeology-Legacy#11]
Whenever I start a server with fossils and fabric API the server fails to start. I've tried it on its own and versions 1.3.0 through 1.3.3 give the same error in the logs, no official crash report is created:

[15:28:41] [main/INFO]: Loading Minecraft 1.21 with Fabric Loader 0.15.11
[15:28:41] [main/INFO]: Fabric is preparing JARs on first launch, this may take a few seconds...
[15:28:41] [main/INFO]: Loading 44 mods:
	- fabric-api 0.102.0+1.21
	   |-- fabric-api-base 0.4.42+6573ed8cd1
	   |-- fabric-api-lookup-api-v1 1.6.68+b5597344d1
	   |-- fabric-biome-api-v1 13.0.29+5bd9f1bcd1
	   |-- fabric-block-api-v1 1.0.22+0af3f5a7d1
	   |-- fabric-block-view-api-v2 1.0.10+6573ed8cd1
	   |-- fabric-blockrenderlayer-v1 1.1.52+0af3f5a7d1
	   |-- fabric-client-tags-api-v1 1.1.15+6573ed8cd1
	   |-- fabric-command-api-v1 1.2.49+f71b366fd1
	   |-- fabric-command-api-v2 2.2.28+6ced4dd9d1
	   |-- fabric-commands-v0 0.2.66+df3654b3d1
	   |-- fabric-content-registries-v0 8.0.16+b5597344d1
	   |-- fabric-convention-tags-v1 2.0.19+7f945d5bd1
	   |-- fabric-convention-tags-v2 2.5.0+c5e2b5c6d1
	   |-- fabric-crash-report-info-v1 0.2.29+0af3f5a7d1
	   |-- fabric-data-attachment-api-v1 1.1.27+6a6dfa19d1
	   |-- fabric-data-generation-api-v1 20.2.16+16c4ae25d1
	   |-- fabric-dimensions-v1 4.0.0+6fc22b99d1
	   |-- fabric-entity-events-v1 1.6.12+6fc22b99d1
	   |-- fabric-events-interaction-v0 0.7.12+ba9dae06d1
	   |-- fabric-game-rule-api-v1 1.0.53+6ced4dd9d1
	   |-- fabric-item-api-v1 11.0.0+afdfc921d1
	   |-- fabric-item-group-api-v1 4.1.4+78017270d1
	   |-- fabric-key-binding-api-v1 1.0.47+0af3f5a7d1
	   |-- fabric-keybindings-v0 0.2.45+df3654b3d1
	   |-- fabric-lifecycle-events-v1 2.3.12+6c1df360d1
	   |-- fabric-loot-api-v2 3.0.14+3f89f5a5d1
	   |-- fabric-loot-api-v3 1.0.2+3f89f5a5d1
	   |-- fabric-message-api-v1 6.0.13+6573ed8cd1
	   |-- fabric-model-loading-api-v1 2.0.0+fe474d6bd1
	   |-- fabric-networking-api-v1 4.2.2+60c3209bd1
	   |-- fabric-object-builder-api-v1 15.2.0+a551f7a4d1
	   |-- fabric-particles-v1 4.0.2+6573ed8cd1
	   |-- fabric-recipe-api-v1 5.0.12+65089712d1
	   |-- fabric-registry-sync-v0 5.1.2+60c3209bd1
	   |-- fabric-renderer-api-v1 3.4.0+c705a49cd1
	   |-- fabric-renderer-indigo 1.7.0+c705a49cd1
	   |-- fabric-renderer-registries-v1 3.2.68+df3654b3d1
	   |-- fabric-rendering-data-attachment-v1 0.3.48+73761d2ed1
	   |-- fabric-rendering-fluids-v1 3.1.6+b5597344d1
	   |-- fabric-rendering-v0 1.1.71+df3654b3d1
	   |-- fabric-rendering-v1 5.0.5+df16efd0d1
	   |-- fabric-resource-conditions-api-v1 4.3.0+8dc279b1d1
	   |-- fabric-resource-loader-v0 1.3.0+56599129d1
	   |-- fabric-screen-api-v1 2.0.24+b5597344d1
	   |-- fabric-screen-handler-api-v1 1.3.86+b5597344d1
	   |-- fabric-sound-api-v1 1.0.23+6573ed8cd1
	   |-- fabric-transfer-api-v1 5.1.16+3dccd343d1
	   \-- fabric-transitive-access-wideners-v1 6.1.0+176f9036d1
	- fabricloader 0.15.11
	   \-- mixinextras 0.3.5
	- fossilslegacy 1.3.3
	   |-- mm 2.3
	   \-- simplelibrary 3.9.2
	        \-- mm 2.3
	- java 21
	- minecraft 1.21
[15:28:41] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/Comma/Downloads/test%20server/libraries/net/fabricmc/sponge-mixin/0.13.3+mixin.0.8.5/sponge-mixin-0.13.3+mixin.0.8.5.jar Service=Knot/Fabric Env=SERVER
[15:28:41] [main/INFO]: Compatibility level set to JAVA_17
[15:28:41] [main/INFO]: Compatibility level set to JAVA_21
[15:28:42] [main/INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.3.5).
[15:28:54] [main/WARN]: No Config Mod Detected: Using Base Config Settings
[15:28:54] [main/INFO]: Definitely not up to no good
[15:28:54] [main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'fossilslegacy'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.15.11.jar:?]
	at net.minecraft.server.Main.main(Main.java:111) [server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [fabric-server-mc.1.21-loader.0.15.11-launcher.1.0.1.jar:1.0.1]
Caused by: java.lang.ExceptionInInitializerError
	at willatendo.fossilslegacy.server.event.ModEvents.commonSetup(ModEvents.java:43) ~[fossilslegacy-1.3.3.jar:?]
	at willatendo.fossilslegacy.FossilsLegacyFabricMod.onInitialize(FossilsLegacyFabricMod.java:20) ~[fossilslegacy-1.3.3.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.11.jar:?]
	... 7 more
Caused by: java.lang.IllegalArgumentException: Unable to find ANALYZER in class net.minecraft.class_5421
	at com.chocohead.mm.api.ClassTinkerers.getEnum(ClassTinkerers.java:274) ~[mm-2.3-dea3eead7ecec716.jar:?]
	at willatendo.simplelibrary.server.util.FabricUtils.createRecipeBookType(FabricUtils.java:8) ~[simplelibrary-3.9.2-ddf3896035798a6b.jar:?]
	at willatendo.fossilslegacy.platform.FossilsFabricHelper.createRecipeBookType(FossilsFabricHelper.java:48) ~[fossilslegacy-1.3.3.jar:?]
	at willatendo.fossilslegacy.server.inventory.FossilsLegacyRecipeBookTypes.<clinit>(FossilsLegacyRecipeBookTypes.java:7) ~[fossilslegacy-1.3.3.jar:?]
	at willatendo.fossilslegacy.server.event.ModEvents.commonSetup(ModEvents.java:43) ~[fossilslegacy-1.3.3.jar:?]
	at willatendo.fossilslegacy.FossilsLegacyFabricMod.onInitialize(FossilsLegacyFabricMod.java:20) ~[fossilslegacy-1.3.3.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.11.jar:?]
	... 7 more

**Comment by willatendo** [comment]
Will be fixed in latest update
